In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('insta.csv')
df.head()

Unnamed: 0  S.No              USERNAME  \
0           0     1         mikequindazzi   
1           1     2       drgorillapaints   
2           2     3    aitrading_official   
3           3     4  opensourcedworkplace   
4           4     5           crea.vision   

                                             Caption  Followers  \
0  Who are #DataScientist and what do they do? >>...       1600   
1  We all know where it’s going. We just have to ...        880   
2  Alexander Barinov: 4 years as CFO in multinati...        255   
3                                               sfad        340   
4  Ever missed a call while your phone was chargi...        304   

                                            Hashtags Time since posted  Likes  
0  #MachineLearning #AI #DataAnalytics #DataScien...          11 hours    139  
1   #deck .#mac #macintosh#sayhello #apple #steve...           2 hours     23  
2  #whoiswho #aitrading #ai #aitradingteam#instat...           2 hours     25  
3  #iot #cre#workplace #CDO #bigdata #technology#...           3 hours     49  
4  #instamachinelearning #instabigdata#instamarke...           3 hours     30

In [3]:
df = df.drop(columns = ['Unnamed: 0','S.No','USERNAME','Caption','Hashtags'])
df.head()

Followers Time since posted  Likes
0       1600          11 hours    139
1        880           2 hours     23
2        255           2 hours     25
3        340           3 hours     49
4        304           3 hours     30

In [4]:
from sklearn.linear_model import LinearRegression

In [5]:
df['Time since posted'] = df['Time since posted'].apply(lambda x:int(x.split()[0]))

In [6]:
df

Followers  Time since posted  Likes
0        1600                 11    139
1         880                  2     23
2         255                  2     25
3         340                  3     49
4         304                  3     30
..        ...                ...    ...
95        614                  3     31
96        450                  3     42
97        182                  3     10
98       2039                  3    222
99        741                  3    109

[100 rows x 3 columns]

In [7]:
from sklearn.model_selection import train_test_split
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
train_x,test_x,train_y,test_y = train_test_split(x,y,random_state=999,test_size=0.2)

In [8]:
x

array([[1600,   11],
       [ 880,    2],
       [ 255,    2],
       [ 340,    3],
       [ 304,    3],
       [1231,    3],
       [ 259,    3],
       [1433,    4],
       [  13,    4],
       [ 450,    7],
       [ 149,    7],
       [2232,    8],
       [1061,    9],
       [ 533,   11],
       [2904,    3],
       [ 971,    3],
       [ 285,    4],
       [ 520,    4],
       [  75,    4],
       [2691,    4],
       [ 966,    5],
       [ 334,    2],
       [1041,    2],
       [4496,    2],
       [ 166,    2],
       [1211,    2],
       [ 265,    2],
       [1618,   20],
       [ 279,    4],
       [ 279,    2],
       [ 828,    2],
       [  12,    2],
       [ 894,    2],
       [ 610,    2],
       [ 226,    2],
       [1168,    2],
       [ 835,    2],
       [ 124,    2],
       [ 193,    2],
       [1600,   14],
       [ 258,    2],
       [ 105,    2],
       [ 273,    2],
       [ 914,    2],
       [ 118,    2],
       [ 122,    2],
       [1180,    2],
       [3139,

In [9]:
y

array([139,  23,  25,  49,  30,  18,  35,  86,  22,  18,  31,  48,  80,
        94,  28,  53,  29,  46,  30,  34, 198,  19,  20,  11,  10,  46,
        25, 148,  43,  37,  90,  19,  14,  30, 273,  13,  93,  24,  18,
       136,  24,   8,  41,  81,  16,  31,  24,  51,  43,  20,  25, 157,
        17,  24,  65, 349,  17,  10,  21,  11,  16,  10,  27,  16,  19,
        29,  31,  41,  19,  40,  21,  50,  20,  10,  35, 119,  11,  55,
        12,  29,  28,  43,  31,  14,  33,  24,  43,   9,  29,  16,  32,
        46,  12,  20,  24,  31,  42,  10, 222, 109], dtype=int64)

In [10]:
train_x

array([[1433,    4],
       [ 258,    2],
       [ 610,    2],
       [ 971,    3],
       [1180,    2],
       [1200,    2],
       [ 226,    2],
       [  11,    3],
       [ 246,    2],
       [1168,    2],
       [ 105,    2],
       [ 966,    5],
       [ 361,    3],
       [ 124,    2],
       [1158,    2],
       [1041,    2],
       [ 140,    2],
       [ 828,    2],
       [1211,    2],
       [  87,    4],
       [ 262,    2],
       [2573,    2],
       [2014,    2],
       [3139,    3],
       [1061,    9],
       [  49,    3],
       [ 614,    3],
       [3448,   24],
       [4496,    2],
       [ 450,    7],
       [ 118,    2],
       [ 179,    2],
       [2039,    3],
       [ 340,    3],
       [ 259,    3],
       [2904,    3],
       [ 145,    2],
       [  66,    3],
       [ 880,    2],
       [ 361,    4],
       [ 935,    4],
       [3147,    2],
       [ 166,    2],
       [ 741,    3],
       [ 273,    2],
       [2785,    7],
       [2372,    2],
       [1231,

In [11]:
train_y

array([ 86,  24,  30,  53,  24,  21, 273,  10,  12,  13,   8, 198,  33,
        24,  29,  20,  28,  90,  46,  24,   9, 119,  29,  51,  80,  24,
        31, 349,  11,  18,  16,  20, 222,  49,  35,  28,  16,  16,  23,
        43,  20,  10,  10, 109,  41,  65,  10,  18,  17,  11,  31, 148,
        42,  55,  94,  30,  14,  81,  43,  46,  50,  27,  25,  19,  24,
        48,  31,  40,  43,  32,  22,  29, 157,  16,  19,  46,  20,  10,
        12,  19], dtype=int64)

In [12]:
test_x

array([[1600,   11],
       [ 371,    2],
       [ 279,    2],
       [ 835,    2],
       [2691,    4],
       [ 265,    2],
       [ 740,    2],
       [1600,   14],
       [ 918,    2],
       [  75,    4],
       [ 149,    7],
       [ 530,    2],
       [ 193,    2],
       [ 181,    2],
       [ 122,    2],
       [2175,    2],
       [ 255,    2],
       [ 460,    2],
       [ 279,    4],
       [  91,    3]], dtype=int64)

In [13]:
test_y

array([139,  19,  37,  93,  34,  25,  35, 136,  21,  30,  31,  17,  18,
        11,  31,  41,  25,  29,  43,  14], dtype=int64)

In [14]:
reg = LinearRegression()
reg.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
from sklearn.metrics import r2_score

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:
y_pred = reg.predict(test_x)

In [18]:
mean_squared_error(test_y,y_pred)

455.857677645365

In [19]:
r2_score(test_y,y_pred)

0.649730259848849

In [20]:
#Working for a better model

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
#Scaler For Input Variables
sc_x = StandardScaler()
train_x_2 = sc_x.fit_transform(train_x)
test_x_2 = sc_x.transform(test_x)
#Scaler for Output Variables
test_y_2 = test_y.reshape((len(test_y),1))
train_y_2 = train_y.reshape((len(train_y),1))
sc_y = StandardScaler()
train_y_2 = sc_y.fit_transform(train_y_2)
test_y_2 = sc_y.transform(test_y_2)

In [23]:
reg2 = LinearRegression()
reg2.fit(train_x,train_y_2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
y_pred_2 = reg2.predict(test_x)

In [25]:
mean_squared_error(sc_y.inverse_transform(test_y_2),sc_y.inverse_transform(y_pred_2))

455.857677645365

In [26]:
mean_squared_error(test_y_2,y_pred_2)

0.13321309196798256

In [27]:
reg.predict([[300,10]])

array([107.30347863])

In [28]:
#Making predictions from both regression models

In [29]:
sc_y.inverse_transform(reg2.predict(sc_x.transform([[300,10]])))

array([[27.44337642]])

In [30]:
r2_score(test_y,y_pred)

0.649730259848849

In [31]:
r2_score(test_y_2,y_pred_2)

0.649730259848849